const spawnData = {
Monday: [
  {hourUTC: 0, location: 'Orc Village', type: 'C'},
  {hourUTC: 0, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 1, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 1, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 2, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 2, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 3, location: 'Orc Village', type: 'M'},
  {hourUTC: 3, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 4, location: 'Orc Village', type: 'C'},
  {hourUTC: 4, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 5, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 5, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 6, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 6, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 7, location: 'Orc Village', type: 'M'},
  {hourUTC: 7, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 8, location: 'Orc Village', type: 'C'},
  {hourUTC: 8, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 9, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 9, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 10, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 10, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 11, location: 'Orc Village', type: 'M'},
  {hourUTC: 11, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 12, location: 'Orc Village', type: 'C'},
  {hourUTC: 12, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 13, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 13, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 14, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 14, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 15, location: 'Orc Village', type: 'M'},
  {hourUTC: 15, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 16, location: 'Orc Village', type: 'C'},
  {hourUTC: 16, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 17, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 17, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 18, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 18, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 19, location: 'Orc Village', type: 'M'},
  {hourUTC: 19, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 20, location: 'Orc Village', type: 'C'},
  {hourUTC: 20, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 21, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 21, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 22, location: 'Orc Village', type: 'M'},
  {hourUTC: 22, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 23, location: 'Orc Village', type: 'C'},
  {hourUTC: 23, location: 'Seal Sanctuary', type: 'M'}
],
Tuesday: [
  {hourUTC: 0, location: 'Orc Village', type: 'M'},
  {hourUTC: 0, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 1, location: 'Orc Village', type: 'C'},
  {hourUTC: 1, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 2, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 2, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 3, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 3, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 4, location: 'Orc Village', type: 'M'},
  {hourUTC: 4, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 5, location: 'Orc Village', type: 'C'},
  {hourUTC: 5, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 6, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 6, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 7, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 7, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 8, location: 'Orc Village', type: 'M'},
  {hourUTC: 8, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 9, location: 'Orc Village', type: 'C'},
  {hourUTC: 9, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 10, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 10, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 11, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 11, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 12, location: 'Orc Village', type: 'M'},
  {hourUTC: 12, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 13, location: 'Orc Village', type: 'C'},
  {hourUTC: 13, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 14, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 14, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 15, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 15, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 16, location: 'Orc Village', type: 'M'},
  {hourUTC: 16, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 17, location: 'Orc Village', type: 'C'},
  {hourUTC: 17, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 18, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 18, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 19, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 19, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 20, location: 'Orc Village', type: 'M'},
  {hourUTC: 20, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 21, location: 'Orc Village', type: 'C'},
  {hourUTC: 21, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 22, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 22, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 23, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 23, location: 'Arkeum Post', type: 'M'}
],
Wednesday: [
  {hourUTC: 0, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 0, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 1, location: 'Orc Village', type: 'M'},
  {hourUTC: 1, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 2, location: 'Orc Village', type: 'C'},
  {hourUTC: 2, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 3, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 3, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 4, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 4, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 5, location: 'Orc Village', type: 'M'},
  {hourUTC: 5, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 6, location: 'Orc Village', type: 'C'},
  {hourUTC: 6, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 7, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 7, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 8, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 8, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 9, location: 'Orc Village', type: 'M'},
  {hourUTC: 9, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 10, location: 'Orc Village', type: 'C'},
  {hourUTC: 10, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 11, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 11, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 12, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 12, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 13, location: 'Orc Village', type: 'M'},
  {hourUTC: 13, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 14, location: 'Orc Village', type: 'C'},
  {hourUTC: 14, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 15, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 15, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 16, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 16, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 17, location: 'Orc Village', type: 'M'},
  {hourUTC: 17, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 18, location: 'Orc Village', type: 'C'},
  {hourUTC: 18, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 19, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 19, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 20, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 20, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 21, location: 'Orc Village', type: 'M'},
  {hourUTC: 21, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 22, location: 'Orc Village', type: 'M'},
  {hourUTC: 22, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 23, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 23, location: 'Seal Sanctuary', type: 'C'}
],
Thursday: [
  {hourUTC: 0, location: 'Orc Village', type: 'C'},
  {hourUTC: 0, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 1, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 1, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 2, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 2, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 3, location: 'Orc Village', type: 'M'},
  {hourUTC: 3, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 4, location: 'Orc Village', type: 'C'},
  {hourUTC: 4, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 5, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 5, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 6, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 6, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 7, location: 'Orc Village', type: 'M'},
  {hourUTC: 7, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 8, location: 'Orc Village', type: 'C'},
  {hourUTC: 8, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 9, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 9, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 10, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 10, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 11, location: 'Orc Village', type: 'M'},
  {hourUTC: 11, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 12, location: 'Orc Village', type: 'C'},
  {hourUTC: 12, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 13, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 13, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 14, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 14, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 15, location: 'Orc Village', type: 'M'},
  {hourUTC: 15, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 16, location: 'Orc Village', type: 'C'},
  {hourUTC: 16, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 17, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 17, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 18, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 18, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 19, location: 'Orc Village', type: 'M'},
  {hourUTC: 19, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 20, location: 'Orc Village', type: 'C'},
  {hourUTC: 20, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 21, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 21, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 22, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 22, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 23, location: 'Orc Village', type: 'M'},
  {hourUTC: 23, location: 'Arkeum Post', type: 'C'}
],
Friday: [
  {hourUTC: 0, location: 'Orc Village', type: 'M'},
  {hourUTC: 0, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 1, location: 'Orc Village', type: 'C'},
  {hourUTC: 1, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 2, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 2, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 3, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 3, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 4, location: 'Orc Village', type: 'M'},
  {hourUTC: 4, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 5, location: 'Orc Village', type: 'C'},
  {hourUTC: 5, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 6, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 6, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 7, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 7, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 8, location: 'Orc Village', type: 'M'},
  {hourUTC: 8, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 9, location: 'Orc Village', type: 'C'},
  {hourUTC: 9, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 10, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 10, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 11, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 11, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 12, location: 'Orc Village', type: 'M'},
  {hourUTC: 12, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 13, location: 'Orc Village', type: 'C'},
  {hourUTC: 13, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 14, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 14, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 15, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 15, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 16, location: 'Orc Village', type: 'M'},
  {hourUTC: 16, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 17, location: 'Orc Village', type: 'C'},
  {hourUTC: 17, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 18, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 18, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 19, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 19, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 20, location: 'Orc Village', type: 'M'},
  {hourUTC: 20, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 21, location: 'Orc Village', type: 'C'},
  {hourUTC: 21, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 22, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 22, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 23, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 23, location: 'Arkeum Post', type: 'M'}
],
Saturday: [
  {hourUTC: 0, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 0, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 1, location: 'Orc Village', type: 'M'},
  {hourUTC: 1, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 2, location: 'Orc Village', type: 'C'},
  {hourUTC: 2, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 3, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 3, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 4, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 4, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 5, location: 'Orc Village', type: 'M'},
  {hourUTC: 5, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 6, location: 'Orc Village', type: 'C'},
  {hourUTC: 6, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 7, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 7, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 8, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 8, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 9, location: 'Orc Village', type: 'M'},
  {hourUTC: 9, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 10, location: 'Orc Village', type: 'C'},
  {hourUTC: 10, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 11, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 11, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 12, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 12, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 13, location: 'Orc Village', type: 'M'},
  {hourUTC: 13, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 14, location: 'Orc Village', type: 'C'},
  {hourUTC: 14, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 15, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 15, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 16, location: 'Orc Village', type: 'C'},
  {hourUTC: 16, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 17, location: 'Orc Village', type: 'M'},
  {hourUTC: 17, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 18, location: 'Orc Village', type: 'C'},
  {hourUTC: 18, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 19, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 19, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 20, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 20, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 21, location: 'Orc Village', type: 'M'},
  {hourUTC: 21, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 22, location: 'Orc Village', type: 'C'},
  {hourUTC: 22, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 23, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 23, location: 'Seal Sanctuary', type: 'C'}
],
Sunday: [
  {hourUTC: 0, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 0, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 1, location: 'Orc Village', type: 'M'},
  {hourUTC: 1, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 2, location: 'Orc Village', type: 'C'},
  {hourUTC: 2, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 3, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 3, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 4, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 4, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 5, location: 'Orc Village', type: 'M'},
  {hourUTC: 5, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 6, location: 'Orc Village', type: 'C'},
  {hourUTC: 6, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 7, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 7, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 8, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 8, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 9, location: 'Orc Village', type: 'M'},
  {hourUTC: 9, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 10, location: 'Orc Village', type: 'C'},
  {hourUTC: 10, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 11, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 11, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 12, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 12, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 13, location: 'Orc Village', type: 'M'},
  {hourUTC: 13, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 14, location: 'Orc Village', type: 'C'},
  {hourUTC: 14, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 15, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 15, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 16, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 16, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 17, location: 'Orc Village', type: 'M'},
  {hourUTC: 17, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 18, location: 'Orc Village', type: 'C'},
  {hourUTC: 18, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 19, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 19, location: 'Seal Sanctuary', type: 'C'},
  {hourUTC: 20, location: 'Shrine of Devotion', type: 'C'},
  {hourUTC: 20, location: 'Arkeum Post', type: 'M'},
  {hourUTC: 21, location: 'Orc Village', type: 'M'},
  {hourUTC: 21, location: 'Arkeum Post', type: 'C'},
  {hourUTC: 22, location: 'Orc Village', type: 'C'},
  {hourUTC: 22, location: 'Seal Sanctuary', type: 'M'},
  {hourUTC: 23, location: 'Shrine of Devotion', type: 'M'},
  {hourUTC: 23, location: 'Seal Sanctuary', type: 'C'}
],
};
