const spawnData = {
Monday: [
  {hourCET: 0, location: 'Orc Village', type: 'C'},
  {hourCET: 0, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 1, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 1, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 2, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 2, location: 'Arkeum Post', type: 'M'},
  {hourCET: 3, location: 'Orc Village', type: 'M'},
  {hourCET: 3, location: 'Arkeum Post', type: 'C'},
  {hourCET: 4, location: 'Orc Village', type: 'C'},
  {hourCET: 4, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 5, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 5, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 6, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 6, location: 'Arkeum Post', type: 'M'},
  {hourCET: 7, location: 'Orc Village', type: 'M'},
  {hourCET: 7, location: 'Arkeum Post', type: 'C'},
  {hourCET: 8, location: 'Orc Village', type: 'C'},
  {hourCET: 8, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 9, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 9, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 10, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 10, location: 'Arkeum Post', type: 'M'},
  {hourCET: 11, location: 'Orc Village', type: 'M'},
  {hourCET: 11, location: 'Arkeum Post', type: 'C'},
  {hourCET: 12, location: 'Orc Village', type: 'C'},
  {hourCET: 12, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 13, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 13, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 14, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 14, location: 'Arkeum Post', type: 'M'},
  {hourCET: 15, location: 'Orc Village', type: 'M'},
  {hourCET: 15, location: 'Arkeum Post', type: 'C'},
  {hourCET: 16, location: 'Orc Village', type: 'C'},
  {hourCET: 16, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 17, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 17, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 18, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 18, location: 'Arkeum Post', type: 'M'},
  {hourCET: 19, location: 'Orc Village', type: 'M'},
  {hourCET: 19, location: 'Arkeum Post', type: 'C'},
  {hourCET: 20, location: 'Orc Village', type: 'C'},
  {hourCET: 20, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 21, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 21, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 22, location: 'Orc Village', type: 'M'},
  {hourCET: 22, location: 'Arkeum Post', type: 'C'},
  {hourCET: 23, location: 'Orc Village', type: 'C'},
  {hourCET: 23, location: 'Seal Sanctuary', type: 'M'}
],
Tuesday: [
  {hourCET: 0, location: 'Orc Village', type: 'M'},
  {hourCET: 0, location: 'Arkeum Post', type: 'C'},
  {hourCET: 1, location: 'Orc Village', type: 'C'},
  {hourCET: 1, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 2, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 2, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 3, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 3, location: 'Arkeum Post', type: 'M'},
  {hourCET: 4, location: 'Orc Village', type: 'M'},
  {hourCET: 4, location: 'Arkeum Post', type: 'C'},
  {hourCET: 5, location: 'Orc Village', type: 'C'},
  {hourCET: 5, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 6, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 6, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 7, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 7, location: 'Arkeum Post', type: 'M'},
  {hourCET: 8, location: 'Orc Village', type: 'M'},
  {hourCET: 8, location: 'Arkeum Post', type: 'C'},
  {hourCET: 9, location: 'Orc Village', type: 'C'},
  {hourCET: 9, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 10, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 10, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 11, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 11, location: 'Arkeum Post', type: 'M'},
  {hourCET: 12, location: 'Orc Village', type: 'M'},
  {hourCET: 12, location: 'Arkeum Post', type: 'C'},
  {hourCET: 13, location: 'Orc Village', type: 'C'},
  {hourCET: 13, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 14, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 14, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 15, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 15, location: 'Arkeum Post', type: 'M'},
  {hourCET: 16, location: 'Orc Village', type: 'M'},
  {hourCET: 16, location: 'Arkeum Post', type: 'C'},
  {hourCET: 17, location: 'Orc Village', type: 'C'},
  {hourCET: 17, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 18, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 18, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 19, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 19, location: 'Arkeum Post', type: 'M'},
  {hourCET: 20, location: 'Orc Village', type: 'M'},
  {hourCET: 20, location: 'Arkeum Post', type: 'C'},
  {hourCET: 21, location: 'Orc Village', type: 'C'},
  {hourCET: 21, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 22, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 22, location: 'Arkeum Post', type: 'M'},
  {hourCET: 23, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 23, location: 'Arkeum Post', type: 'M'}
],
Wednesday: [
  {hourCET: 0, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 0, location: 'Arkeum Post', type: 'M'},
  {hourCET: 1, location: 'Orc Village', type: 'M'},
  {hourCET: 1, location: 'Arkeum Post', type: 'C'},
  {hourCET: 2, location: 'Orc Village', type: 'C'},
  {hourCET: 2, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 3, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 3, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 4, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 4, location: 'Arkeum Post', type: 'M'},
  {hourCET: 5, location: 'Orc Village', type: 'M'},
  {hourCET: 5, location: 'Arkeum Post', type: 'C'},
  {hourCET: 6, location: 'Orc Village', type: 'C'},
  {hourCET: 6, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 7, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 7, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 8, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 8, location: 'Arkeum Post', type: 'M'},
  {hourCET: 9, location: 'Orc Village', type: 'M'},
  {hourCET: 9, location: 'Arkeum Post', type: 'C'},
  {hourCET: 10, location: 'Orc Village', type: 'C'},
  {hourCET: 10, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 11, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 11, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 12, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 12, location: 'Arkeum Post', type: 'M'},
  {hourCET: 13, location: 'Orc Village', type: 'M'},
  {hourCET: 13, location: 'Arkeum Post', type: 'C'},
  {hourCET: 14, location: 'Orc Village', type: 'C'},
  {hourCET: 14, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 15, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 15, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 16, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 16, location: 'Arkeum Post', type: 'M'},
  {hourCET: 17, location: 'Orc Village', type: 'M'},
  {hourCET: 17, location: 'Arkeum Post', type: 'C'},
  {hourCET: 18, location: 'Orc Village', type: 'C'},
  {hourCET: 18, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 19, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 19, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 20, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 20, location: 'Arkeum Post', type: 'M'},
  {hourCET: 21, location: 'Orc Village', type: 'M'},
  {hourCET: 21, location: 'Arkeum Post', type: 'C'},
  {hourCET: 22, location: 'Orc Village', type: 'M'},
  {hourCET: 22, location: 'Arkeum Post', type: 'C'},
  {hourCET: 23, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 23, location: 'Seal Sanctuary', type: 'C'}
],
Thursday: [
  {hourCET: 0, location: 'Orc Village', type: 'C'},
  {hourCET: 0, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 1, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 1, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 2, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 2, location: 'Arkeum Post', type: 'M'},
  {hourCET: 3, location: 'Orc Village', type: 'M'},
  {hourCET: 3, location: 'Arkeum Post', type: 'C'},
  {hourCET: 4, location: 'Orc Village', type: 'C'},
  {hourCET: 4, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 5, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 5, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 6, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 6, location: 'Arkeum Post', type: 'M'},
  {hourCET: 7, location: 'Orc Village', type: 'M'},
  {hourCET: 7, location: 'Arkeum Post', type: 'C'},
  {hourCET: 8, location: 'Orc Village', type: 'C'},
  {hourCET: 8, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 9, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 9, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 10, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 10, location: 'Arkeum Post', type: 'M'},
  {hourCET: 11, location: 'Orc Village', type: 'M'},
  {hourCET: 11, location: 'Arkeum Post', type: 'C'},
  {hourCET: 12, location: 'Orc Village', type: 'C'},
  {hourCET: 12, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 13, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 13, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 14, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 14, location: 'Arkeum Post', type: 'M'},
  {hourCET: 15, location: 'Orc Village', type: 'M'},
  {hourCET: 15, location: 'Arkeum Post', type: 'C'},
  {hourCET: 16, location: 'Orc Village', type: 'C'},
  {hourCET: 16, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 17, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 17, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 18, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 18, location: 'Arkeum Post', type: 'M'},
  {hourCET: 19, location: 'Orc Village', type: 'M'},
  {hourCET: 19, location: 'Arkeum Post', type: 'C'},
  {hourCET: 20, location: 'Orc Village', type: 'C'},
  {hourCET: 20, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 21, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 21, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 22, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 22, location: 'Arkeum Post', type: 'M'},
  {hourCET: 23, location: 'Orc Village', type: 'M'},
  {hourCET: 23, location: 'Arkeum Post', type: 'C'}
],
Friday: [
  {hourCET: 0, location: 'Orc Village', type: 'M'},
  {hourCET: 0, location: 'Arkeum Post', type: 'C'},
  {hourCET: 1, location: 'Orc Village', type: 'C'},
  {hourCET: 1, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 2, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 2, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 3, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 3, location: 'Arkeum Post', type: 'M'},
  {hourCET: 4, location: 'Orc Village', type: 'M'},
  {hourCET: 4, location: 'Arkeum Post', type: 'C'},
  {hourCET: 5, location: 'Orc Village', type: 'C'},
  {hourCET: 5, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 6, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 6, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 7, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 7, location: 'Arkeum Post', type: 'M'},
  {hourCET: 8, location: 'Orc Village', type: 'M'},
  {hourCET: 8, location: 'Arkeum Post', type: 'C'},
  {hourCET: 9, location: 'Orc Village', type: 'C'},
  {hourCET: 9, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 10, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 10, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 11, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 11, location: 'Arkeum Post', type: 'M'},
  {hourCET: 12, location: 'Orc Village', type: 'M'},
  {hourCET: 12, location: 'Arkeum Post', type: 'C'},
  {hourCET: 13, location: 'Orc Village', type: 'C'},
  {hourCET: 13, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 14, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 14, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 15, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 15, location: 'Arkeum Post', type: 'M'},
  {hourCET: 16, location: 'Orc Village', type: 'M'},
  {hourCET: 16, location: 'Arkeum Post', type: 'C'},
  {hourCET: 17, location: 'Orc Village', type: 'C'},
  {hourCET: 17, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 18, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 18, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 19, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 19, location: 'Arkeum Post', type: 'M'},
  {hourCET: 20, location: 'Orc Village', type: 'M'},
  {hourCET: 20, location: 'Arkeum Post', type: 'C'},
  {hourCET: 21, location: 'Orc Village', type: 'C'},
  {hourCET: 21, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 22, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 22, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 23, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 23, location: 'Arkeum Post', type: 'M'}
],
Saturday: [
  {hourCET: 0, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 0, location: 'Arkeum Post', type: 'M'},
  {hourCET: 1, location: 'Orc Village', type: 'M'},
  {hourCET: 1, location: 'Arkeum Post', type: 'C'},
  {hourCET: 2, location: 'Orc Village', type: 'C'},
  {hourCET: 2, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 3, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 3, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 4, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 4, location: 'Arkeum Post', type: 'M'},
  {hourCET: 5, location: 'Orc Village', type: 'M'},
  {hourCET: 5, location: 'Arkeum Post', type: 'C'},
  {hourCET: 6, location: 'Orc Village', type: 'C'},
  {hourCET: 6, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 7, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 7, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 8, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 8, location: 'Arkeum Post', type: 'M'},
  {hourCET: 9, location: 'Orc Village', type: 'M'},
  {hourCET: 9, location: 'Arkeum Post', type: 'C'},
  {hourCET: 10, location: 'Orc Village', type: 'C'},
  {hourCET: 10, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 11, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 11, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 12, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 12, location: 'Arkeum Post', type: 'M'},
  {hourCET: 13, location: 'Orc Village', type: 'M'},
  {hourCET: 13, location: 'Arkeum Post', type: 'C'},
  {hourCET: 14, location: 'Orc Village', type: 'C'},
  {hourCET: 14, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 15, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 15, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 16, location: 'Orc Village', type: 'C'},
  {hourCET: 16, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 17, location: 'Orc Village', type: 'M'},
  {hourCET: 17, location: 'Arkeum Post', type: 'C'},
  {hourCET: 18, location: 'Orc Village', type: 'C'},
  {hourCET: 18, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 19, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 19, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 20, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 20, location: 'Arkeum Post', type: 'M'},
  {hourCET: 21, location: 'Orc Village', type: 'M'},
  {hourCET: 21, location: 'Arkeum Post', type: 'C'},
  {hourCET: 22, location: 'Orc Village', type: 'C'},
  {hourCET: 22, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 23, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 23, location: 'Seal Sanctuary', type: 'C'}
],
Sunday: [
  {hourCET: 0, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 0, location: 'Arkeum Post', type: 'M'},
  {hourCET: 1, location: 'Orc Village', type: 'M'},
  {hourCET: 1, location: 'Arkeum Post', type: 'C'},
  {hourCET: 2, location: 'Orc Village', type: 'C'},
  {hourCET: 2, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 3, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 3, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 4, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 4, location: 'Arkeum Post', type: 'M'},
  {hourCET: 5, location: 'Orc Village', type: 'M'},
  {hourCET: 5, location: 'Arkeum Post', type: 'C'},
  {hourCET: 6, location: 'Orc Village', type: 'C'},
  {hourCET: 6, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 7, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 7, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 8, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 8, location: 'Arkeum Post', type: 'M'},
  {hourCET: 9, location: 'Orc Village', type: 'M'},
  {hourCET: 9, location: 'Arkeum Post', type: 'C'},
  {hourCET: 10, location: 'Orc Village', type: 'C'},
  {hourCET: 10, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 11, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 11, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 12, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 12, location: 'Arkeum Post', type: 'M'},
  {hourCET: 13, location: 'Orc Village', type: 'M'},
  {hourCET: 13, location: 'Arkeum Post', type: 'C'},
  {hourCET: 14, location: 'Orc Village', type: 'C'},
  {hourCET: 14, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 15, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 15, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 16, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 16, location: 'Arkeum Post', type: 'M'},
  {hourCET: 17, location: 'Orc Village', type: 'M'},
  {hourCET: 17, location: 'Arkeum Post', type: 'C'},
  {hourCET: 18, location: 'Orc Village', type: 'C'},
  {hourCET: 18, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 19, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 19, location: 'Seal Sanctuary', type: 'C'},
  {hourCET: 20, location: 'Shrine of Devotion', type: 'C'},
  {hourCET: 20, location: 'Arkeum Post', type: 'M'},
  {hourCET: 21, location: 'Orc Village', type: 'M'},
  {hourCET: 21, location: 'Arkeum Post', type: 'C'},
  {hourCET: 22, location: 'Orc Village', type: 'C'},
  {hourCET: 22, location: 'Seal Sanctuary', type: 'M'},
  {hourCET: 23, location: 'Shrine of Devotion', type: 'M'},
  {hourCET: 23, location: 'Seal Sanctuary', type: 'C'}
]
};
