// spawns.js

const spawnData = [
  { day: 'Wednesday', hourUTC: 0, location: 'Shrine of Devotion', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 0, location: 'Arkeum Post', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 1, location: 'Orc Village', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 1, location: 'Arkeum Post', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 2, location: 'Orc Village', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 2, location: 'Seal Sanctum', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 3, location: 'Shrine of Devotion', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 3, location: 'Seal Sanctum', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 4, location: 'Shrine of Devotion', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 4, location: 'Arkeum Post', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 5, location: 'Orc Village', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 5, location: 'Arkeum Post', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 6, location: 'Orc Village', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 6, location: 'Seal Sanctum', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 7, location: 'Shrine of Devotion', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 7, location: 'Seal Sanctum', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 8, location: 'Shrine of Devotion', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 8, location: 'Arkeum Post', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 9, location: 'Orc Village', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 9, location: 'Arkeum Post', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 10, location: 'Orc Village', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 10, location: 'Seal Sanctum', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 11, location: 'Shrine of Devotion', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 11, location: 'Seal Sanctum', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 12, location: 'Shrine of Devotion', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 12, location: 'Arkeum Post', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 13, location: 'Orc Village', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 13, location: 'Arkeum Post', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 14, location: 'Orc Village', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 14, location: 'Seal Sanctum', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 15, location: 'Shrine of Devotion', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 15, location: 'Seal Sanctum', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 16, location: 'Shrine of Devotion', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 16, location: 'Arkeum Post', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 17, location: 'Orc Village', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 17, location: 'Arkeum Post', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 18, location: 'Orc Village', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 18, location: 'Seal Sanctum', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 19, location: 'Shrine of Devotion', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 19, location: 'Seal Sanctum', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 20, location: 'Shrine of Devotion', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 20, location: 'Arkeum Post', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 21, location: 'Orc Village', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 21, location: 'Arkeum Post', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 22, location: 'Orc Village', type: 'C', image: '' },
  { day: 'Wednesday', hourUTC: 22, location: 'Arkeum Post', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 23, location: 'Shrine of Devotion', type: 'M', image: '' },
  { day: 'Wednesday', hourUTC: 23, location: 'Seal Sanctum', type: 'C', image: '' }
];

if (typeof module !== 'undefined') {
  module.exports = spawnData;
}